/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',

        cream: 'var(--cream)',
        sand: '#fdfbf7',
        ink: 'var(--ink)',
        coral: 'var(--coral)',
        sky: 'var(--sky)',
        lime: 'var(--lime)',
        mint: 'var(--mint)',
        magenta: 'var(--magenta)',
        amber: 'var(--amber)',

        // Semantic backward compatibility
        paper: 'var(--background)',
        surface: 'var(--card)',
        yellow: 'var(--amber)',
        blue: 'var(--sky)',
        purple: 'var(--magenta)',
      },
      borderWidth: {
        2: '2px',
        3: '3px',
        4: '4px',
        5: '5px',
      },
      borderRadius: {
        sm: 'calc(var(--radius) - 4px)',
        md: 'calc(var(--radius) - 2px)',
        lg: 'var(--radius)',
        xl: 'calc(var(--radius) + 4px)',
        '2xl': 'calc(var(--radius) + 8px)',
        '3xl': 'calc(var(--radius) + 12px)',
        '4xl': 'calc(var(--radius) + 16px)',
        brutal: '1.25rem',
      },
      boxShadow: {
        'hard-shadow': '10px 10px 0 var(--ink)',
        'hard-shadow-sm': '5px 5px 0 var(--ink)',
        'hard-shadow-xs': '4px 4px 0 var(--ink)',
        'brutal-xs': '4px 4px 0 var(--ink)',
        'brutal-sm': '5px 5px 0 var(--ink)',
        brutal: '10px 10px 0 var(--ink)',
        'brutal-md': '8px 8px 0 var(--ink)',
        'brutal-lg': '10px 10px 0 var(--ink)',
        'brutal-xl': '14px 14px 0 var(--ink)',
        none: '0 0 0 0 var(--ink)',
      },
      fontFamily: {
        grotesk: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
        serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
        mono: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
        sans: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      },
    },
  },
  plugins: [],
};
